// 화면 문구 (한국어, 시안 그대로) — 한곳에 모아 둔다. 영어를 더할 때 shared/i18n 의 사전으로 옮긴다.

export const S = {
  appName: 'litecode',

  connectIntro: '데스크탑의 litecode 에 연결합니다. 데스크탑에서 설정 › 모바일을 열어 QR 을 띄워 주세요.',
  scanQr: 'QR 스캔',
  scanHint: '데스크탑 화면의 QR 을 네모 안에 맞춰 주세요',
  closeScanner: '닫기',
  cameraDenied: '카메라 권한이 없어 QR 을 읽을 수 없습니다. 아래 "주소와 코드 직접 입력" 으로 연결해 주세요.',
  findingDesktop: '데스크탑을 찾는 중…',
  addressLabel: '데스크탑 주소',
  codeLabel: '연결 코드',
  codeHint: '데스크탑의 설정 › 모바일 › 기기 연결에 보이는 숫자 2자리',
  deviceNameLabel: '이 기기 이름',
  connect: '연결',
  waitingForAllow: '데스크탑의 허용을 기다리는 중…',
  revokedOnDesktop: '데스크탑에서 이 기기의 연결을 해제했습니다. 다시 연결해 주세요.',
  pairFailure: {
    'bad-address': '주소를 읽을 수 없습니다. 192.168.0.12:47600 처럼 입력해 주세요.',
    'not-loopback': '암호화하지 않은 연결(http://)은 이 컴퓨터 안(에뮬레이터)에서만 됩니다. 앞의 http:// 를 지워 주세요.',
    'bad-code': '연결 코드는 숫자 2자리입니다. 데스크탑 화면의 코드를 그대로 입력해 주세요.',
    'no-name': '이 기기 이름을 입력해 주세요.',
    'wrong-code': '코드가 틀렸거나 만료됐습니다. 데스크탑에서 기기 연결을 다시 눌러 새 코드를 확인해 주세요.',
    denied: '데스크탑에서 연결을 거절했습니다.',
    timeout: '데스크탑에서 허용을 누르지 않아 시간이 지났습니다. 다시 시도해 주세요.',
    blocked: '여러 번 실패해 잠시 막혔습니다. 몇 분 뒤 다시 시도해 주세요.',
    'net-timeout': '데스크탑이 답하지 않습니다. 폰과 PC 가 같은 와이파이(또는 VPN)에 있는지, PC 방화벽이 litecode 를 막지 않는지 확인해 주세요. 회사 와이파이가 기기끼리의 연결을 막을 수도 있습니다(클라이언트 격리).',
    refused: 'PC 에는 닿았지만 연결을 받지 않습니다. 데스크탑의 설정 › 기능에서 "모바일 연결" 이 켜져 있는지, 포트가 맞는지 확인해 주세요.',
    'fingerprint-mismatch': '데스크탑 인증서의 지문이 QR 과 다릅니다. 다른 PC 이거나 연결이 가로채졌을 수 있습니다. 데스크탑에서 QR 을 다시 띄워 주세요.',
    'qr-foreign': 'litecode 연결 QR 이 아닙니다. 데스크탑의 설정 › 모바일에 뜬 QR 을 스캔해 주세요.',
    'qr-version': '이 앱이 모르는 QR 형식입니다. 앱을 최신으로 바꿔 주세요.',
    'qr-expired': 'QR 이 만료됐습니다. 데스크탑에서 기기 연결을 다시 눌러 새 QR 을 띄워 주세요.',
    'qr-invalid': 'QR 을 읽었지만 내용이 올바르지 않습니다. 데스크탑에서 QR 을 다시 띄워 주세요.',
    'old-android': '이 폰의 Android 버전에서는 사내망 연결을 쓸 수 없습니다 — Android 10 이상이 필요합니다. (에뮬레이터의 이 컴퓨터 안 연결은 영향 없음)',
    'tls-failed': '데스크탑에는 닿았지만 암호화 연결(TLS)을 맺지 못했습니다. 아래 자세한 내용을 알려 주세요.',
    'connection-broken': '데스크탑에는 닿았지만 연결이 도중에 끊겼습니다. 다시 시도해 주세요.',
    unreachable: '데스크탑에 닿지 못했습니다. 데스크탑의 설정 › 기능에서 "모바일 연결" 이 켜져 있는지, 주소가 맞는지 확인해 주세요.',
    failed: '연결하지 못했습니다. 다시 시도해 주세요.',
  },
  notice: {
    'desktop-only': '이 대화는 전체 권한 모드라 데스크탑에서만 보낼 수 있습니다.',
    'answer-desktop-only': '이 대화는 전체 권한 모드라 데스크탑에서만 답할 수 있습니다.',
    'send-failed': '보내지 못했습니다. 연결을 확인하고 다시 보내 주세요.',
    elsewhere: '다른 기기에서 이미 답했습니다.',
    failed: '요청을 처리하지 못했습니다. 연결을 확인해 주세요.',
  },
  noConversations: '아직 대화가 없습니다.',
  fingerprintNone: '없음 (이 컴퓨터 안 연결)',
  enterManually: '주소와 코드 직접 입력',
  allowOnDesktop: '데스크탑에서 허용을 눌러 주세요',
  checkCode: '확인 코드가 데스크탑 화면의 코드와 같은지 보세요.',
  checkFingerprint: '데스크탑의 허용 창에 뜬 지문과 같은지 보세요. 다르면 허용하지 마세요.',
  fingerprintChanged: '지문이 달라졌습니다 (데스크탑을 다시 설치했거나 다른 PC 일 수 있습니다). 새로 연결하세요.',
  fingerprintChangedShort: '지문이 달라졌습니다 — 새로 연결하세요',
  lanUnsupported: (apiLevel: number) =>
    `이 폰의 Android 버전(API ${apiLevel})에서는 사내망 연결을 쓸 수 없습니다 — Android 10 이상이 필요합니다. 에뮬레이터의 이 컴퓨터 안 연결(http://10.0.2.2 등)은 영향 없습니다.`,
  connectFootnote: '같은 사내망(Wi-Fi 또는 VPN)에 있어야 연결됩니다. 대화 내용은 데스크탑에만 저장됩니다.',

  // 연결 방법 고르기 (이슈 #211, 시안 _workspace/mock-ble Main·Bt·Fail)
  connectTitle: '데스크탑에 연결',
  connectChooseIntro: '연결할 방법을 직접 고릅니다. 고른 방법으로만 붙습니다.',
  pairedDevice: '짝지은 기기',
  connectMethod: '연결 방법',
  carrierName: { wifi: 'Wi-Fi (사내망)', bluetooth: '블루투스' },
  carrierShort: { wifi: 'Wi-Fi', bluetooth: '블루투스' },
  carrierHint: {
    wifi: '빠릅니다. 폰과 PC 가 같은 네트워크에 있어야 합니다.',
    bluetooth: '느립니다. 네트워크가 없어도 되고, PC 가까이(약 10m)에 있어야 합니다.',
  },
  connectVia: { wifi: 'Wi-Fi 로 연결', bluetooth: '블루투스로 연결' },
  tryVia: { wifi: 'Wi-Fi 로 시도', bluetooth: '블루투스로 시도' },
  switchTo: { wifi: 'Wi-Fi 로 바꾸기', bluetooth: '블루투스로 바꾸기' },
  connectingNow: '연결 중…',
  notConnected: '연결 안 됨',
  connectRemember: '마지막에 고른 방법을 기억합니다. 안 되더라도 다른 방법으로 몰래 넘어가지 않습니다.',
  retry: '다시 시도',
  cannotReach: { wifi: 'Wi-Fi 로 닿지 않습니다', bluetooth: '블루투스로 연결하지 못했습니다' },
  wifiFailure: (address: string) => `${address} 에 연결하지 못했습니다. 같은 네트워크인지, 데스크탑의 "사내망 연결" 이 켜져 있는지 확인해 주세요.`,
  bluetoothFailure: {
    'no-key': '이 짝에는 블루투스 키가 없습니다. 데스크탑에서 블루투스 연결을 켜고 QR 로 다시 짝지어야 합니다.',
    unsupported: '이 폰은 블루투스 저전력(BLE)을 쓸 수 없습니다.',
    permission: '"근처 기기" 권한이 없어 블루투스를 쓸 수 없습니다. 시스템 설정 › 앱 › litecode › 권한에서 허용한 뒤 다시 시도해 주세요.',
    'bluetooth-off': '폰의 블루투스가 꺼져 있습니다. 블루투스를 켠 뒤 다시 시도해 주세요.',
    'not-found': '데스크탑을 찾지 못했습니다 — 데스크탑에서 블루투스 연결이 꺼져 있거나 10m 보다 멉니다.',
    'location-off': '데스크탑을 찾지 못했습니다. 이 폰(Android 11 이하)은 위치가 켜져 있어야 블루투스 기기를 찾습니다 — 위치를 켜고, 데스크탑에서 블루투스 연결이 켜져 있는지 확인해 주세요.',
    'connect-failed': '데스크탑을 찾았지만 연결하지 못했습니다. 데스크탑 가까이에서 다시 시도해 주세요.',
    'handshake-failed': '데스크탑과 보안 연결을 맺지 못했습니다. 계속 안 되면 데스크탑의 블루투스 키가 바뀐 것입니다 — QR 로 다시 짝지어 주세요.',
  },
  bluetoothLost: '블루투스 연결이 끊겼습니다. 데스크탑 가까이에서 다시 시도해 주세요.',
  bluetoothNotYet: '블루투스로 시도 를 누르기 전에는 블루투스를 켜거나 주변을 찾지 않습니다. 누르면 "근처 기기" 허용을 한 번 물어봅니다.',
  bluetoothBadge: '블루투스 · 느림',
  bluetoothInfo: '블루투스로 연결됨. 느린 연결이라 긴 대화는 여는 데 시간이 걸립니다.',
  loadingHistory: '이전 대화 불러오기',
  receivingKb: (kb: number) => `${kb} KB 받는 중`,
  connectMethodValue: (name: string) => `연결 방법: ${name}`,
  needsAction: '연결하려면 확인이 필요합니다',

  switchProject: '프로젝트 바꾸기',
  settings: '설정',
  conversations: '대화',
  newConversation: '새 대화',
  untitled: '새 대화',
  reconnecting: (seconds: number) => `다시 연결 중 · ${seconds}초`,
  unresponsive: '데스크탑 응답 없음 (잠자기?)',
  revoked: '연결이 해제됐습니다',
  connecting: '연결 중',

  needsAnswer: '답 필요',
  running: '진행 중',
  done: '완료',
  failed: '실패',
  interrupted: '중단됨',
  declined: '거절됨',
  subtasks: (count: number) => `하위 작업 ${count}`,
  approveCommand: '명령 실행 승인',
  approveEdit: '파일 수정 승인',
  approveOther: '실행 승인',
  question: '질문',
  answerOnDesktop: '이 질문은 폰에서 답할 수 없습니다. 데스크탑에서 답해 주세요.',
  hookFollowUp: '턴 끝 훅이 이어서 보냄',
  delegatedFrom: (title: string) => `다른 대화에서 온 지시 · ${title}`,
  delegatedFromProject: (project: string, title: string) => `다른 프로젝트에서 온 지시 · ${project} · ${title}`,

  now: '지금',
  secondsAgo: (n: number) => `${n}초`,
  minutesAgo: (n: number) => `${n}분`,
  hoursAgo: (n: number) => `${n}시간`,
  yesterday: '어제',
  daysAgo: (n: number) => `${n}일`,

  backToList: '대화 목록으로',
  jobs: (count: number) => `작업 ${count}`,
  runningJobs: (count: number) => `도는 작업 ${count}개`,
  seconds: (n: number) => `${n}초`,
  thinkCount: (n: number) => `생각 ${n}`,
  toolCount: (n: number) => `도구 ${n}`,
  think: '생각',
  reject: '거절',
  allowOnce: '한 번 허용',
  queued: (count: number, text: string) => `대기 ${count} · "${text}"`,
  takeBack: '되돌리기',
  messagePlaceholder: '메시지를 입력하세요…',
  message: '메시지',
  mode: { plan: '계획', build: '기본', ask: '매번 묻기', full: '전체 권한' },
  modeLabel: (name: string) => `모드: ${name}`,
  stop: '중지',
  send: '보내기',

  back: '뒤로',
  connectedDesktop: '연결된 데스크탑',
  connected: '연결됨',
  disconnected: '끊김',
  address: '주소',
  fingerprint: '지문',
  lastConnected: '마지막 연결',
  justNow: '방금',
  disconnect: '연결 해제',
  general: '일반',
  language: '언어',
  korean: '한국어',
  theme: '테마',
  system: '시스템',
  keepAlive: '연결 유지',
  keepAliveHint: '앱을 닫아도 연결을 유지해 답 필요·완료 알림을 받습니다',
  keepAliveLimit: '꺼 두면 앱이 뒤에 있는 동안에는 알림이 오지 않고, 다시 열 때 이어서 받습니다. 켜면 상단에 알림이 계속 떠 있습니다.',
  notifications: '알림',
  notificationsHint: '답이 필요하거나 작업이 끝나면 알립니다',
  permissionOff: '알림 권한이 꺼져 있습니다 — 시스템 설정에서 켜 주세요',
  openSystemSettings: '설정 열기',
  channelAttention: '답 필요',
  channelResult: '완료·실패',
  channelKeepAlive: '연결 유지',
  keepAliveTitle: 'litecode',
  keepAliveText: (desktop: string) => `데스크탑에 연결됨 · ${desktop}`,
  about: (version: string) => `litecode 모바일 ${version} · 모델, 프로젝트, MCP 설정은 데스크탑에서 바꿉니다.`,
} as const
