// 화면 문구 (한국어, 시안 그대로) — 한곳에 모아 둔다. 영어를 더할 때 shared/i18n 의 사전으로 옮긴다.

export const S = {
  appName: 'litecode',

  connectIntro: '데스크탑의 litecode 에 연결합니다. 데스크탑에서 설정 › 모바일을 열어 QR 을 띄워 주세요.',
  scanQr: 'QR 스캔',
  enterManually: '주소와 코드 직접 입력',
  allowOnDesktop: '데스크탑에서 허용을 눌러 주세요',
  checkCode: '확인 코드가 데스크탑 화면의 코드와 같은지 보세요.',
  connectFootnote: '같은 사내망(Wi-Fi 또는 VPN)에 있어야 연결됩니다. 대화 내용은 데스크탑에만 저장됩니다.',

  switchProject: '프로젝트 바꾸기',
  settings: '설정',
  conversations: '대화',
  newConversation: '새 대화',
  untitled: '새 대화',
  reconnecting: (seconds: number) => `다시 연결 중 · ${seconds}초`,
  unresponsive: '데스크탑 응답 없음 (잠자기?)',
  revoked: '연결이 해제됐습니다',
  connecting: '연결 중',

  needsAnswer: '답 필요',
  running: '진행 중',
  done: '완료',
  failed: '실패',
  interrupted: '중단됨',
  declined: '거절됨',
  subtasks: (count: number) => `하위 작업 ${count}`,
  approveCommand: '명령 실행 승인',
  approveEdit: '파일 수정 승인',
  approveOther: '실행 승인',
  question: '질문',

  now: '지금',
  secondsAgo: (n: number) => `${n}초`,
  minutesAgo: (n: number) => `${n}분`,
  hoursAgo: (n: number) => `${n}시간`,
  yesterday: '어제',
  daysAgo: (n: number) => `${n}일`,

  backToList: '대화 목록으로',
  jobs: (count: number) => `작업 ${count}`,
  runningJobs: (count: number) => `도는 작업 ${count}개`,
  seconds: (n: number) => `${n}초`,
  thinkCount: (n: number) => `생각 ${n}`,
  toolCount: (n: number) => `도구 ${n}`,
  think: '생각',
  reject: '거절',
  allowOnce: '한 번 허용',
  queued: (count: number, text: string) => `대기 ${count} · "${text}"`,
  takeBack: '되돌리기',
  messagePlaceholder: '메시지를 입력하세요…',
  message: '메시지',
  mode: { plan: '계획', build: '기본', ask: '매번 묻기', full: '전체 권한' },
  modeLabel: (name: string) => `모드: ${name}`,
  stop: '중지',
  send: '보내기',

  back: '뒤로',
  connectedDesktop: '연결된 데스크탑',
  connected: '연결됨',
  disconnected: '끊김',
  address: '주소',
  fingerprint: '지문',
  lastConnected: '마지막 연결',
  justNow: '방금',
  disconnect: '연결 해제',
  general: '일반',
  language: '언어',
  korean: '한국어',
  theme: '테마',
  system: '시스템',
  keepAlive: '연결 유지',
  keepAliveHint: '앱을 닫아도 연결을 유지해 답 필요·완료 알림을 받습니다',
  about: (version: string) => `litecode 모바일 ${version} · 모델, 프로젝트, MCP 설정은 데스크탑에서 바꿉니다.`,
} as const
