// 화면 문구 (한국어, 시안 그대로) — 한곳에 모아 둔다. 영어를 더할 때 shared/i18n 의 사전으로 옮긴다.

export const S = {
  appName: 'litecode',

  connectIntro: '데스크탑의 litecode 에 연결합니다. 데스크탑에서 설정 › 모바일 › 기기 연결을 눌러 주소와 코드를 확인해 주세요.',
  scanQrSoon: 'QR 스캔 · 준비 중',
  addressLabel: '데스크탑 주소',
  codeLabel: '연결 코드',
  codeHint: '데스크탑의 설정 › 모바일 › 기기 연결에 보이는 12자',
  deviceNameLabel: '이 기기 이름',
  connect: '연결',
  waitingForAllow: '데스크탑의 허용을 기다리는 중…',
  revokedOnDesktop: '데스크탑에서 이 기기의 연결을 해제했습니다. 다시 연결해 주세요.',
  pairFailure: {
    'bad-address': '주소를 읽을 수 없습니다. 10.0.2.2:47600 처럼 입력해 주세요.',
    'not-loopback': '아직 이 컴퓨터 안(에뮬레이터)에서만 연결됩니다 — 사내망 연결은 준비 중입니다.',
    'bad-code': '연결 코드는 12자입니다. 데스크탑 화면의 코드를 그대로 입력해 주세요.',
    'no-name': '이 기기 이름을 입력해 주세요.',
    'wrong-code': '코드가 틀렸거나 만료됐습니다. 데스크탑에서 기기 연결을 다시 눌러 새 코드를 확인해 주세요.',
    denied: '데스크탑에서 연결을 거절했습니다.',
    timeout: '데스크탑에서 허용을 누르지 않아 시간이 지났습니다. 다시 시도해 주세요.',
    blocked: '여러 번 실패해 잠시 막혔습니다. 몇 분 뒤 다시 시도해 주세요.',
    unreachable: '데스크탑에 닿지 못했습니다. 데스크탑의 설정 › 기능에서 "모바일 연결" 이 켜져 있는지, 주소가 맞는지 확인해 주세요.',
    failed: '연결하지 못했습니다. 다시 시도해 주세요.',
  },
  notice: {
    'desktop-only': '이 대화는 전체 권한 모드라 데스크탑에서만 보낼 수 있습니다.',
    'send-failed': '보내지 못했습니다. 연결을 확인하고 다시 보내 주세요.',
    elsewhere: '다른 기기에서 이미 답했습니다.',
    failed: '요청을 처리하지 못했습니다. 연결을 확인해 주세요.',
  },
  noConversations: '아직 대화가 없습니다.',
  fingerprintNone: '없음 (이 컴퓨터 안 연결)',
  enterManually: '주소와 코드 직접 입력',
  allowOnDesktop: '데스크탑에서 허용을 눌러 주세요',
  checkCode: '확인 코드가 데스크탑 화면의 코드와 같은지 보세요.',
  connectFootnote: '지금은 데스크탑과 같은 컴퓨터 안(에뮬레이터)에서만 연결됩니다. 대화 내용은 데스크탑에만 저장됩니다.',

  switchProject: '프로젝트 바꾸기',
  settings: '설정',
  conversations: '대화',
  newConversation: '새 대화',
  untitled: '새 대화',
  reconnecting: (seconds: number) => `다시 연결 중 · ${seconds}초`,
  unresponsive: '데스크탑 응답 없음 (잠자기?)',
  revoked: '연결이 해제됐습니다',
  connecting: '연결 중',

  needsAnswer: '답 필요',
  running: '진행 중',
  done: '완료',
  failed: '실패',
  interrupted: '중단됨',
  declined: '거절됨',
  subtasks: (count: number) => `하위 작업 ${count}`,
  approveCommand: '명령 실행 승인',
  approveEdit: '파일 수정 승인',
  approveOther: '실행 승인',
  question: '질문',
  answerOnDesktop: '이 질문은 폰에서 답할 수 없습니다. 데스크탑에서 답해 주세요.',
  hookFollowUp: '턴 끝 훅이 이어서 보냄',
  delegatedFrom: (title: string) => `다른 대화에서 온 지시 · ${title}`,
  delegatedFromProject: (project: string, title: string) => `다른 프로젝트에서 온 지시 · ${project} · ${title}`,

  now: '지금',
  secondsAgo: (n: number) => `${n}초`,
  minutesAgo: (n: number) => `${n}분`,
  hoursAgo: (n: number) => `${n}시간`,
  yesterday: '어제',
  daysAgo: (n: number) => `${n}일`,

  backToList: '대화 목록으로',
  jobs: (count: number) => `작업 ${count}`,
  runningJobs: (count: number) => `도는 작업 ${count}개`,
  seconds: (n: number) => `${n}초`,
  thinkCount: (n: number) => `생각 ${n}`,
  toolCount: (n: number) => `도구 ${n}`,
  think: '생각',
  reject: '거절',
  allowOnce: '한 번 허용',
  queued: (count: number, text: string) => `대기 ${count} · "${text}"`,
  takeBack: '되돌리기',
  messagePlaceholder: '메시지를 입력하세요…',
  message: '메시지',
  mode: { plan: '계획', build: '기본', ask: '매번 묻기', full: '전체 권한' },
  modeLabel: (name: string) => `모드: ${name}`,
  stop: '중지',
  send: '보내기',

  back: '뒤로',
  connectedDesktop: '연결된 데스크탑',
  connected: '연결됨',
  disconnected: '끊김',
  address: '주소',
  fingerprint: '지문',
  lastConnected: '마지막 연결',
  justNow: '방금',
  disconnect: '연결 해제',
  general: '일반',
  language: '언어',
  korean: '한국어',
  theme: '테마',
  system: '시스템',
  keepAlive: '연결 유지',
  keepAliveHint: '앱을 닫아도 연결을 유지해 답 필요·완료 알림을 받습니다',
  keepAliveLimit: '꺼 두면 앱이 뒤에 있는 동안에는 알림이 오지 않고, 다시 열 때 이어서 받습니다. 켜면 상단에 알림이 계속 떠 있습니다.',
  notifications: '알림',
  notificationsHint: '답이 필요하거나 작업이 끝나면 알립니다',
  permissionOff: '알림 권한이 꺼져 있습니다 — 시스템 설정에서 켜 주세요',
  openSystemSettings: '설정 열기',
  channelAttention: '답 필요',
  channelResult: '완료·실패',
  channelKeepAlive: '연결 유지',
  keepAliveTitle: 'litecode',
  keepAliveText: (desktop: string) => `데스크탑에 연결됨 · ${desktop}`,
  about: (version: string) => `litecode 모바일 ${version} · 모델, 프로젝트, MCP 설정은 데스크탑에서 바꿉니다.`,
} as const
