// 채팅 답 모양·진행 표시에 새로 넣은 화면 문구 — 영문 키 한 곳에 모은다 (언어 설정 라운드와 합친 뒤 i18n 사전으로 옮긴다).
// 기존 문구(복사·보내기 등)는 여기로 옮기지 않았다 — 실물 테스트 셀렉터가 그 글자에 기댄다

export const chatStrings = {
  /** 끝난 턴 머리 — dsh "Took {duration}" 자리 */
  completedIn: (duration: string) => `완료 · ${duration}`,
  completed: '완료',
  failedAfter: (duration: string) => `실패 · ${duration}`,
  failed: '실패',
  interruptedAfter: (duration: string) => `중단됨 · ${duration}`,
  interrupted: '중단됨',
  /** 진행 중 맨 아래 줄 — dsh "Deep diving for {duration}" 자리 */
  workingFor: (duration: string) => `작업 중 · ${duration}`,
  working: '작업 중',
  showWork: '작업 내용 펼치기',
  hideWork: '작업 내용 접기',
  think: '생각',
  thinking: '생각하는 중',
  toolPreparing: '준비 중',
  seconds: (s: number) => `${s}초`,
  minutes: (m: number, s: number) => `${m}분 ${s}초`,
  hours: (h: number, m: number) => `${h}시간 ${m}분`,
  /** 언어 없는 코드 블록 머리 — dsh "Code block" 자리 */
  codeBlock: '코드 블록',
  wrapOff: '줄바꿈 끄기',
  wrapOn: '줄바꿈 켜기',
  copyMessage: '메시지 복사',
  messageCopied: '복사됨',
  revealFile: (file: string) => `${file} — 파일 관리자에서 보기`,
  minimap: '대화 위치',
  minimapTurn: (index: number, text: string) => `${index}. ${text}`,
  /** `!명령` 결과 카드 */
  shellRunning: '실행 중',
  shellExit: (code: number) => `종료 코드 ${code}`,
  shellStopped: '중단됨',
  shellTimeout: (seconds: number) => `${seconds}초를 넘겨 중단됨`,
  shellError: (reason: string) => `실행하지 못함: ${reason}`,
  shellStop: '중단',
  shellNoOutput: '(출력 없음)',
  shellTruncated: (kb: number) => `출력이 ${kb}KB 에서 잘렸습니다`,
  shellExpand: '전체 보기',
  shellCollapse: '접기',
  shellLocalOnly: '대화 맥락에 들어가지 않았습니다 — AI 는 이 결과를 모릅니다',
  shellShare: 'AI 에게 보내기',
  shellShared: '보냄',
  shellSharedNote: '대화 맥락에 넣었습니다 — 다음 질문 때 AI 가 함께 봅니다',
  shellShareBusy: '답을 기다리는 중에는 보낼 수 없습니다 — 턴이 끝난 뒤에 보내세요',
  shellShareNoModel: '모델을 먼저 고르세요',
  shellShareFailed: (reason: string) => `보내지 못했습니다: ${reason}`,
} as const
